id: ID9DD7434
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T22:03:09+00:00'
last_modified: '2022-06-16T05:35:51.674025+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ6027
  title: འཇའ་ཚོན་སྙིང་པོའི་ཆོས་སྤྱོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0CFE:
      image_group_id: I1KG1019
      title: ''
      total_pages: 522
      order: 1
      base_file: 0CFE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
